import Anthropic from "@anthropic-ai/sdk";
import { z } from "zod";

const FindingSchema = z.object({
  severity: z.enum(["high", "medium", "low"]),
  file: z.string().min(1),
  line: z.number().int().positive().nullable().optional(),
  issue: z.string().min(1),
  suggestion: z.string().min(1),
});

const ReviewSchema = z.object({
  summary: z.string().min(1),
  bugRisks: z.array(FindingSchema),
  securityIssues: z.array(FindingSchema),
  styleFlags: z.array(FindingSchema),
  testCoverageGaps: z.array(FindingSchema),
});

export type ReviewResult = z.infer<typeof ReviewSchema>;

const fallbackReview: ReviewResult = {
  summary:
    "Automated review is temporarily running in fallback mode. Configure CLAUDE_API_KEY to enable full PR analysis.",
  bugRisks: [],
  securityIssues: [],
  styleFlags: [],
  testCoverageGaps: [],
};

function extractJson(content: string) {
  const fencedMatch = content.match(/```json([\s\S]*?)```/i);
  if (fencedMatch?.[1]) {
    return fencedMatch[1].trim();
  }

  const firstBrace = content.indexOf("{");
  const lastBrace = content.lastIndexOf("}");

  if (firstBrace === -1 || lastBrace === -1 || lastBrace <= firstBrace) {
    return null;
  }

  return content.slice(firstBrace, lastBrace + 1);
}

function normalizeResult(review: ReviewResult): ReviewResult {
  return {
    summary: review.summary,
    bugRisks: review.bugRisks.slice(0, 8),
    securityIssues: review.securityIssues.slice(0, 8),
    styleFlags: review.styleFlags.slice(0, 8),
    testCoverageGaps: review.testCoverageGaps.slice(0, 8),
  };
}

export async function analyzePullRequestWithClaude(input: {
  repoFullName: string;
  prTitle: string;
  prBody: string;
  diff: string;
}): Promise<ReviewResult> {
  const apiKey = process.env.CLAUDE_API_KEY;

  if (!apiKey) {
    return fallbackReview;
  }

  const client = new Anthropic({ apiKey });
  const model = process.env.CLAUDE_MODEL ?? "claude-sonnet-4-20250514";

  const prompt = [
    `Repository: ${input.repoFullName}`,
    `Pull Request Title: ${input.prTitle}`,
    `Pull Request Description: ${input.prBody || "No description provided."}`,
    "Code diff:",
    input.diff || "No patch data received.",
    "",
    "Review this pull request as a senior reviewer.",
    "Return strict JSON with fields: summary, bugRisks, securityIssues, styleFlags, testCoverageGaps.",
    "Each finding object must include severity (high|medium|low), file, line (nullable integer), issue, suggestion.",
    "Only include findings supported by the diff and keep language direct and concrete.",
  ].join("\n");

  const response = await client.messages.create({
    model,
    max_tokens: 1700,
    temperature: 0.1,
    messages: [
      {
        role: "user",
        content: prompt,
      },
    ],
  });

  const text = response.content
    .filter((block) => block.type === "text")
    .map((block) => block.text)
    .join("\n")
    .trim();

  const candidateJson = extractJson(text);
  if (!candidateJson) {
    return fallbackReview;
  }

  try {
    const parsed = JSON.parse(candidateJson);
    return normalizeResult(ReviewSchema.parse(parsed));
  } catch {
    return fallbackReview;
  }
}

function formatFindings(title: string, findings: ReviewResult["bugRisks"]) {
  if (findings.length === 0) {
    return `### ${title}\nNo high-confidence issues detected in this category.`;
  }

  const lines = findings.map((finding, index) => {
    const lineRef = finding.line ? `:${finding.line}` : "";
    return [
      `${index + 1}. **${finding.severity.toUpperCase()}** \`${finding.file}${lineRef}\``,
      `Issue: ${finding.issue}`,
      `Suggestion: ${finding.suggestion}`,
    ].join("\n");
  });

  return `### ${title}\n${lines.join("\n\n")}`;
}

export function formatReviewMarkdown(review: ReviewResult) {
  return [
    "## PR Review AI Report",
    "",
    review.summary,
    "",
    formatFindings("Bug Risks", review.bugRisks),
    "",
    formatFindings("Security Issues", review.securityIssues),
    "",
    formatFindings("Style Flags", review.styleFlags),
    "",
    formatFindings("Test Coverage Gaps", review.testCoverageGaps),
    "",
    "---",
    "_Generated by PR Review AI using Claude Sonnet 4._",
  ].join("\n");
}
